### PR TITLE
ci(root): update ls lint version & config wd-180

### PR DESCRIPTION
**Pull request by what1s1ove**

### CODE REVIEW

**Comment by loeffel-io** [comment]
Can you please provide more informations what you try to archive with `regex:([.a-z0-9]*)([-.][a-z0-9]+)*`

First quick look: you missed `.d.ts` 

I would a recommend a config like this: 

```yaml
ls:
  .dir: kebab-case
  .*: regex:([.a-z0-9]*)([-.][a-z0-9]+)* # dont know why 
  .*.*: regex:([.a-z0-9]*)([-.][a-z0-9]+)* # match .d.ts
  .md: SCREAMING_SNAKE_CASE # rename your readme.md to README.md

  .github:
    .dir: regex:([.a-z]*)*
    # you could add here more to check - only .dir is checked for .github and sub directories

ignore:
  - .git
  - '**/node_modules'
  - '**/build'
```

**Comment by loeffel-io** [comment]
Checked out your repo 

This should do the job: 

```
ls:
  .dir: kebab-case
  .*: kebab-case
  .*.*: kebab-case
  .md: SCREAMING_SNAKE_CASE # rename your readme.md to README.md

  .github:
    .dir: regex:[.]*[a-z]+
    .yml: kebab-case

ignore:
  - .git
  - '**/node_modules'
  - '**/build'
  - '**/index.md' # <-- 
```

**Comment by what1s1ove** [comment]
> Can you please provide more informations what you try to archive with `regex:([.a-z0-9]*)([-.][a-z0-9]+)*`
> 
> First quick look: you missed `.d.ts`
> 
> I would a recommend a config like this:
> 
> ```yaml
> ls:
>   .dir: kebab-case
>   .*: regex:([.a-z0-9]*)([-.][a-z0-9]+)* # dont know why 
>   .*.*: regex:([.a-z0-9]*)([-.][a-z0-9]+)* # match .d.ts
>   .md: SCREAMING_SNAKE_CASE # rename your readme.md to README.md
> 
>   .github:
>     .dir: regex:([.a-z]*)*
>     # you could add here more to check - only .dir is checked for .github and sub directories
> 
> ignore:
>   - .git
>   - '**/node_modules'
>   - '**/build'
> ```

Hey @loeffel-io! Thank you for your advice!

> Can you please provide more informations what you try to archive with regex:([.a-z0-9]*)([-.][a-z0-9]+)*

This regex was previously used for files like timeline-filter.type.js, as the simple kebab-case option would still complain about such a name. I've had this regex for a very long time, since the early versions of ls-lint. It's great to see that I can now remove it! Thank you!

Regarding MD files. Honestly, I don't want to rename the readme and add index.md to the ignore list 🥲 since there is a high chance that other MD files with different names will appear. As I understand it, there's no other way to make ls-lint not complain about the root file CHANGELOG.md, except for what you described?

**Comment by loeffel-io** [comment]
Got it - Yes, there is no way by design

**Pull request merged**
